
1.Exception was introduced in which java version

a..Java 1	(ans)
b.Java 2
c.Java 3
d.Java 4

2..
What keyword is used to explicitly raise a exception?

a.catch
b..throw	(ans)
c.throws
d.raise

3..Which of these are java.lang.Error in exception handling in java

a.VirtualMachineError
b.IOError
c.AssertionError
d.ThreadDeath
e..All	(ans)

4..In which condition will the finally block will not be executed?

a.When some Error occurs
b.When Exception is raised
c..When System.Exit(1) is called	(ans)
d.In all the cases


4..What will be output of following program -

https://drive.google.com/uc?id=0B1iLyaHj2nSLLVg3cE9DTUJzVkE

a.runtime exception
b.program will compile
c..program won't compile	(ans)
d.

5.What will be output of following program -
https://drive.google.com/uc?id=0B1iLyaHj2nSLMWJRWl8yRG1RNE0

a.runtime exception
b..method return -> finally	(ans)
c.method return -> catch
d.compile timeError

6.output?
class Base extends Exception {}
class Derived extends Base  {}
 
public class Main {
  public static void main(String args[]) {
   // some other stuff
   try {
       // Some monitored code
       throw new Derived();
    }
    catch(Base b)     { 
       System.out.println("Caught base class exception"); 
    }
    catch(Derived d)  { 
       System.out.println("Caught derived class exception"); 
    }
  }
} 

A.
	
Caught base class exception
b.	
Caught derived class exception
C.
	
Compiler Error because derived is not throwable
d..	
Compiler Error because base class exception is caught before derived class	(ans)

7.output?
class Test
{
    public static void main(String[] args)
    {
        try
        {
            int a[]= {1, 2, 3, 4};
            for (int i = 1; i <= 4; i++)
            {
                System.out.println ("a[" + i + "]=" + a[i] + "n");
            }
        }
         
        catch (Exception e)
        {
            System.out.println ("error = " + e);
        }
         
        catch (ArrayIndexOutOfBoundsException e)
        {
            System.out.println ("ArrayIndexOutOfBoundsException");
        }
    }
}
a..
Compiler error	(ans)
B.	
Run time error
C.	
ArrayIndexOutOfBoundsException
D.	
Error Code is printed
E.	
Array is printed

8.
Predict the output of the following program.
class Test
{   int count = 0;
 
    void A() throws Exception
    {
        try
        {
            count++;
             
            try
            {
                count++;
 
                try
                {
                    count++;
                    throw new Exception();
 
                }
                 
                catch(Exception ex)
                {
                    count++;
                    throw new Exception();
                }
            }
             
            catch(Exception ex)
            {
                count++;
            }
        }
         
        catch(Exception ex)
        {
            count++;
        }
 
    }
 
    void display()
    {
        System.out.println(count);
    }
 
    public static void main(String[] args) throws Exception
    {
        Test obj = new Test();
        obj.A();
        obj.display();
    }
}

a.
4
b..	
5	(ans)
c.	
6
D.	
Compilation error
	
9.What will be output of following program -
https://drive.google.com/uc?id=0B1iLyaHj2nSLeE9QbzcwQ0k5MkU

a.abc
b.abcd
c..runtime exception	(ans)
d.compile timeError

/////10.
What will be output of following exception handling code in java -

https://drive.google.com/uc?id=0B1iLyaHj2nSLUFZjckw0b0pjLWs

a.ade
b.adb
c.bcde
d.adbe

11.What will be output of following exception handling code in java -

https://drive.google.com/uc?id=0B1iLyaHj2nSLOUxHYWM4UjQtZE0

a.SubClass method
b..compilation error	(ans)
c.runtime exception
d.superClass method

12.Which is invalid about throws in Exception handling in java?

a.throws can propagate exception to calling method
b.throws can be used to throw multiple exception at time.
c..throws is used inside method to throw exception	(ans)
d.None of these

13.Which of these exceptions are propagated automatically in java?

a.IOException
b..NullPointerException	(ans)
c.ClassNotFoundException
d.SQLException

14.URL throws an exception called
A. IllegalURLException
B. URLException
C. MalformedHostException
D.. MalformedURLException	(ans)

15.What will be output of following program -

https://drive.google.com/uc?id=0B1iLyaHj2nSLX1R3cUwxT21SemM

a.compile timeError
b..UserDefinedException will be thrown	(ans)
c.UserDefinedException will be thrown and end will be present in output
d.None

16.Which of these is not a good exception handling practice?

a.Throw exceptions when the method cannot handle the exception, and more importantly, must be handled by the caller
b..log the exception and bubble it	(ans)
c.Bubble the exception if the method cannot handle it.
d.Throw the exception right away

17.Which of these not a Error?

a.VirtualMachineError
b..ClassNotFoundError	(ans)
c.OutOfMemoryError
d.IOError

18.What will be output of following exception handling program -

https://drive.google.com/uc?id=0B1iLyaHj2nSLS2FYTUoxeU9lVms

a.after calling m()
b..runtime exception	(ans)
c.program won't compile
d.None

19. The toString ( ) method in the user-defined exception class is overridden.
True/False
Ans : True

20. What will happen to the Exception object after exception handling?
Ans : It will go for Garbage Collector. And frees the memory.







